<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Areauom extends Admin_Controller
{

    function __construct()
    {
        parent::__construct();
        $this->load->model('Areauom_model');
    }

    function index()
    {
        $this->load->library('form_validation');
        $this->form_validation->set_rules('name', 'AreaUom ', 'required');


        if ($this->form_validation->run()) {
            // Left is database column name, right side is value posted from form
            $params = array(
                'name' => $this->input->post('name'),

                'created_by' => $this->session->userdata('id')
            );
            $this->Areauom_model->add_areauom($params);
            $this->session->set_flashdata('success', 'Areauom added successfuly');
            redirect('areauom');
        } else {


            $data['_view'] = 'areauom/index';

            $this->load->view('layouts/main', $data);
        }
    }
    function get_list()
    {
        $columns = array(
            0 => 'name',

            1 => 'id'
        );

        // This is for sorting and pagination, it will mstly stay the same
        $limit = $this->input->post('length');
        $start = $this->input->post('start');
        $order = $columns[$this->input->post('order')[0]['column']];
        $dir = $this->input->post('order')[0]['dir'];
        // This is for sorting and pagination, it will mstly stay the same end


        $totalData = $this->Areauom_model->get_all_areauom_count();

        $totalFiltered = $totalData;

        if (empty($this->input->post('search')['value'])) {
            $posts = $this->Areauom_model->get_all_areauom($limit, $start, $order, $dir);
        } else {
            $search = $this->input->post('search')['value'];

            $posts =  $this->Areauom_model->areauom_search($limit, $start, $search, $order, $dir);

            $totalFiltered = $this->Areauom_model->areauom_search_count($search);
        }

        $data = array();
        if (!empty($posts)) {
            foreach ($posts as $post) {
                $nestedData['name'] = $post->name;

                $nestedData['actions'] = "<button class='btn btn-warning btn-xs btn-edit' code='" . $post->id . "'>Edit</button>&nbsp;<button class='btn btn-danger btn-xs btn-delete' code='" . $post->id . "'>Delete</button>";

                $data[] = $nestedData;
            }
        }

        $json_data = array(
            "draw"            => intval($this->input->post('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $data
        );

        echo json_encode($json_data);
    }

    public function edit_country($id)
    {
        # code...
    }

    public function delete_areauom($id)
    {
        echo $this->Areauom_model->delete_areauom($id);
    }

    public function update_areauom($id)
    {
        echo $this->Areauom_model->update_areauom($id,['name'=>$this->input->post('name')]);
    }
}
