<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Current_stock extends Admin_Controller
{

    function __construct()
    {
        parent::__construct();
        $this->load->model('Currentstock_model');
        $this->load->model('Productcategory_model');
    }

    function index()
    {
        $params = "";
        if (isset($_POST['search'])) {
            $todate = $this->input->post('todate');
            $category_product = $this->input->post('category_product');
            $product_id = $this->input->post('product_id');
            
            $params = array(
                'todate' => $todate,
                'category_product' => $category_product,
                'product_id' => $product_id
            );
        } else {
            $params = array(
                'todate' => date('y-m-d'),
                'category_product' => "",
                'product_id' => ""
            );
        }
        $data['products'] = $this->Currentstock_model->get_products_search($params);
        $data['product_categories'] = $this->Productcategory_model->get_productcategory_for_dd();
        $data['_view'] = 'report/current_stock';
        $this->load->view('layouts/main', $data);
    }

    function get_category_products($cat_id)
    {
        
        $data = $this->Currentstock_model->get_category_products($cat_id);
        echo "<option value=''>Select</option>";
        foreach ($data['products'] as $pro) {
            echo "<option value='" . $pro['id'] . "'>" . $pro['product_name'] . "( " . $pro['product_code'] . " )" . "</option>";
        }
    }
}
