<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard extends Admin_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dashboard_model');
    }

    function index()
    {
 
        $data['_view'] = 'dashboard';
            // num rows example
    $this->db->select('*');
    // $this->db->where('mac', $mac);
    $query = $this->db->get('language');
    $num = $query->num_rows();
    $row = $query->row_array();
    if($num<1)
    {
        $language = array(
                    'name'   => 'site_lang',
                    'value'  => 'english',
                    'expire' => 604800
                );
        $this->input->set_cookie($language);
    }
    else{
        $lang = array(
                    'name'   => 'site_lang',
                    'value'  => $row['language_name'],
                    'expire' => 604800
                );
        $this->input->set_cookie($lang);
    }

        if ($this->session->userdata('active_farm')) {
            $LiveStockdata = $this->Dashboard_model->AnimalsCountByStatus('animals', $this->session->userdata('active_farm'));
            $LiveStock = json_decode(json_encode($LiveStockdata), true);
            $data['chart_data'] = '[' . implode(",", $LiveStock) . ']';

            $CattleManagementdata = $this->Dashboard_model->AnimalsCountByStatus('fattening_animals', $this->session->userdata('active_farm'));
            $CattleManagement = json_decode(json_encode($CattleManagementdata), true);
            $data['cattle_chart_data'] = '[' . implode(",", $CattleManagement) . ']';


            $yeildMilkdata = $this->Dashboard_model->AnimalsyeildMilk($this->session->userdata('active_farm'));
            $animalNames = $animalYeildqty = "";
            if (!empty($yeildMilkdata)) {
                $yeildMilk = json_decode(json_encode($yeildMilkdata), true);
                foreach ($yeildMilk as $j) {
                    $animalNames .= '"' . $j['animal_name'] . '( ' . $j['animal_code'] . ' )' . '"' . ", ";
                    $animalYeildqty .= $j['animalTotalQty'] . ", ";
                }
            } else {
                $animalNames = null;
                $animalYeildqty = null;
            }

            $data['animal_Names'] = '[' . rtrim($animalNames, ", ") . ']';
            $data['animal_Yeildqty'] = '[' . rtrim($animalYeildqty, ", ") . ']';


            $morningYeild = $eveningYeild = $afternoonYeild =  $dateYeild = "";
            $milk_Yeild_By_Date = $this->Dashboard_model->AnimalsmilkYeildByDate($this->session->userdata('active_farm'));

            if (!empty($milk_Yeild_By_Date)) {
                $yeildMilkByDate = json_decode(json_encode($milk_Yeild_By_Date), true);
                foreach ($yeildMilkByDate as $k) {
                    $morningYeild .= $k['Morning'] . ", ";
                    $eveningYeild .= $k['Evening'] . ", ";
                    $afternoonYeild .= $k['Afternoon'] . ", ";
                    $dateYeild .= '"'.$k['date'] . '", ';
                }
            } else {
                    $morningYeild = null;
                    $eveningYeild = null;
                    $afternoonYeild = null;
                    $dateYeild = null;
            }

            $data['morningYeild'] = '[' . rtrim($morningYeild, ", ") . ']';
            $data['eveningYeild'] = '[' . rtrim($eveningYeild, ", ") . ']';
            $data['afternoonYeild'] = '[' . rtrim($afternoonYeild, ", ") . ']';
            $data['dateYeild'] = '[' . rtrim($dateYeild, ", ") . ']';

            

            $data['expenseChart'] = json_encode($this->Dashboard_model->get_expense_by_categories());

        } else {
            $data['chart_data'] = '[]';
            $data['cattle_chart_data'] = '[]';
            $data['animal_Names'] = '[]';
            $data['animal_Yeildqty'] = '[]';
            $data['morningYeild'] = '[]';
            $data['eveningYeild'] = '[]';
            $data['afternoonYeild'] = '[]';
            $data['dateYeild'] = '[]';
        }


        $this->load->view('layouts/main', $data);
    }

    function setfarm()
    {
        $this->load->library('form_validation');
        $this->form_validation->set_rules('farm_id', ' Farm ID', 'required');
        if ($this->form_validation->run()) {
            $this->session->set_userdata('active_farm', $this->input->post('farm_id'));
            $this->session->set_userdata('active_farm_name', $this->input->post('active_farm_name'));
            $this->session->set_userdata('quarantine_new_animal', $this->input->post('quarantine_new_animal'));
            $this->session->set_userdata('quarantine_days', $this->input->post('quarantine_days'));
            redirect('dashboard');
        } else {
            redirect('dashboard');
        }
    }

    function test(){
        var_dump($_SESSION);
    }

    function language()
    {
      $lang=$this->input->post('lang');
      $query = $this->db->get('language');
    $num = $query->num_rows();
    // echo
    if($num<1)
    {
        $data = array(
        'language_name'=>$lang
    );
         $this->db->insert('language',$data);   
    }
    else{
      $this->db->update('language', array('language_name' => $lang));  
    }
      
      // echo $lang;exit;   
        $language = array(
                    'name'   => 'site_lang',
                    'value'  => $lang,
                    'expire' => 604800
                );
        $this->input->set_cookie($language);
        echo $lang;
    }
}
