<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Itemuom extends Admin_Controller
{

    function __construct()
    {
        parent::__construct();
        $this->load->model('Itemuom_model');
    }

    function index()
    {
        $this->load->library('form_validation');
        $this->form_validation->set_rules('name', 'UOM Name ', 'required');
        $this->form_validation->set_rules('symbol', 'UOM Symbol ', 'required');


        if ($this->form_validation->run()) {
            // Left is database column name, right side is value posted from form
            $params = array(
                'name' => $this->input->post('name'),
                'symbol' => $this->input->post('symbol'),
                'created_by' => $this->session->userdata('id')
            );
            $this->Itemuom_model->add_itemuom($params);
            $this->session->set_flashdata('success', 'Item UOM added successfuly');
            redirect('itemuom');
        } else {


            $data['_view'] = 'itemuom/index';

            $this->load->view('layouts/main', $data);
        }
    }
    function get_list()
    {
        $columns = array(
            0 => 'name',
            1 => 'symbol',
            2 => 'id'
        );

        // This is for sorting and pagination, it will mstly stay the same
        $limit = $this->input->post('length');
        $start = $this->input->post('start');
        $order = $columns[$this->input->post('order')[0]['column']];
        $dir = $this->input->post('order')[0]['dir'];
        // This is for sorting and pagination, it will mstly stay the same end


        $totalData = $this->Itemuom_model->get_all_itemuom_count();

        $totalFiltered = $totalData;

        if (empty($this->input->post('search')['value'])) {
            $posts = $this->Itemuom_model->get_all_itemuom($limit, $start, $order, $dir);
        } else {
            $search = $this->input->post('search')['value'];

            $posts =  $this->Itemuom_model->itemuom_search($limit, $start, $search, $order, $dir);

            $totalFiltered = $this->Itemuom_model->itemuom_search_count($search);
        }

        $data = array();
        if (!empty($posts)) {
            foreach ($posts as $post) {
                $nestedData['name'] = $post->name;
                $nestedData['symbol'] = $post->symbol;

                $nestedData['actions'] = "<button class='btn btn-warning btn-xs btn-edit' code='" . $post->id . "'>Edit</button>&nbsp;<button class='btn btn-danger btn-xs btn-delete' code='" . $post->id . "'>Delete</button>";

                $data[] = $nestedData;
            }
        }

        $json_data = array(
            "draw"            => intval($this->input->post('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $data
        );

        echo json_encode($json_data);
    }


    public function delete_itemuom($id)
    {
        echo $this->Itemuom_model->delete_itemuom($id);
    }

    public function update_itemuom($id)
    {
        echo $this->Itemuom_model->update_itemuom($id,['name'=>$this->input->post('name'),'symbol'=>$this->input->post('symbol')]);
    }
}
