<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class LandManagementData extends Admin_Controller
{

    function __construct()
    {
        parent::__construct();
        $this->load->model('LandManagementData_model');
        
    }

    function index()
    {

        $this->load->library('form_validation');
        $this->form_validation->set_rules('land_management_data', 'Name', 'required');
        $this->form_validation->set_rules('land_management_type_id', 'Type', 'required');

        if ($this->form_validation->run()) {
            // Left is database column name, right side is value posted from form
            $params = array(
                'land_management_data' => $this->input->post('land_management_data'),
                'land_management_type_id' => $this->input->post('land_management_type_id'),
                'status'=>ACTIVE,
                'created_by' => $this->session->userdata('id')
            );
            $this->LandManagementData_model->add($params);
            $this->session->set_flashdata('success', 'Land Management Data added successfuly');
            redirect('landManagementData');
        } else {
            $data['LandManagementType'] = $this->LandManagementData_model->get_all_LandManagementType_for_dd();
            $data['_view'] = 'LandManagementData/index';
            $this->load->view('layouts/main', $data);
        }
    }
    function get_list()
    {
        // This is for the sorting of columns, right side should match the column name of db
        $columns = array(
            0 => 'id',
            1 => 'land_management_data',
            2 => 'land_management_type_id'       
        );

        // This is for sorting and pagination, it will mstly stay the same
        $limit = $this->input->post('length');
        $start = $this->input->post('start');
        $order = $columns[$this->input->post('order')[0]['column']];
        $dir = $this->input->post('order')[0]['dir'];
        // This is for sorting and pagination, it will mstly stay the same end

    
        $totalData = $this->LandManagementData_model->get_all_LandManagementData_count();

        $totalFiltered = $totalData;

        if (empty($this->input->post('search')['value'])) {
            $posts = $this->LandManagementData_model->get_all_LandManagementData($limit, $start, $order, $dir);
        } else {
            $search = $this->input->post('search')['value'];

            $posts =  $this->LandManagementData_model->LandManagementData_search($limit, $start, $search, $order, $dir);

            $totalFiltered = $this->LandManagementData_model->LandManagementData_search_count($search);
        }

        $data = array();
        if (!empty($posts)) {
            foreach ($posts as $post) {
                $nestedData['land_management_data'] = $post->land_management_data;
                $nestedData['land_management_type_id'] = $post->land_management_type;
                $nestedData['actions'] = "<button class='btn btn-warning btn-xs btn-edit' code='".$post->id."'>Edit</button>&nbsp;<button class='btn btn-danger btn-xs btn-delete' code='".$post->id."'>Delete</button>";

                $data[] = $nestedData;
            }
        }

        $json_data = array(
            "draw"            => intval($this->input->post('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $data
        );

        echo json_encode($json_data);
    }
    public function edit_country($id)
    {
        # code...
    }

    public function delete($id){
        $this->LandManagementData_model->delete($id);
        echo "1";
    }

    public function update($id){
        $this->load->library('form_validation');
        $this->form_validation->set_rules('land_management_data', 'Name', 'required');
        $this->form_validation->set_rules('land_management_type_id', 'Type', 'required');

        if ($this->form_validation->run()) {
            $this->LandManagementData_model->update($id,[
                'land_management_data' => $this->input->post('land_management_data'),
                'land_management_type_id' => $this->input->post('land_management_type_id'),
                'status'=>ACTIVE,
                'created_by' => $this->session->userdata('id')
            ]);
            echo 1;
        }

    }
}
