<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Marking_area extends Admin_Controller{
    
    function __construct()
    {
        parent::__construct();
        $this->load->model('Marking_area_model');
    }

    
    function index()
    {
        
   
            $data['_view'] = 'markingarea/index';

            $this->load->view('layouts/main',$data);
        
    }

    function add_batch(){
        
        $batchCount = $this->Marking_area_model->batch_count();
        $landBatch = array(
                        'batch_no' => $batchCount+1,
                        'batch_data'=> $this->input->post('batch_data'),
                        'created_by' => $this->session->userdata('id'),
                        'status' => ACTIVE,
                        'farm_id' => $this->session->userdata('active_farm')
                    );
        
        $insert = $this->db->insert('land_batch', $landBatch);

        if($insert){
            return true;
        } else {
            return false;
        }

        
    }
    function remove_batch(){
        $delete =  $this->db->where(array('id' => $this->input->post('batch_id')))->update('land_batch',['status'=>DELETED]);

        if($delete){
            return true;
        } else {
            return false;
        }

        
    }

    function get_batch(){
        $this->db->select('*');
            $this->db->where_in('farm_id', $this->session->userdata('active_farm'));
            $this->db->where_in('status', ACTIVE);
            $batch_data = $this->db->get('land_batch')->result_array();
            foreach ($batch_data as $key => $value) { 
                $batchData = explode("-",$value['batch_data']);
                
            echo     "<div class='card'><div class='card-header' id='heading$key'><h2 class='mb-0'>";
            echo     "<button type='button' class='btn btn-link' data-toggle='collapse' data-target='#collapse$key'><i class='fa fa-angle-right'></i> Batch No ".$value['batch_no']."</button><a onclick=removeBatch(".$value['id'].")><span  class='fa fa-trash btn btn-link' style='float:right;'></span></a>";									
            echo     "</h2></div><div id='collapse$key' class='collapse' aria-labelledby='heading$key' data-parent='#accordionExample'>";
            echo     "<div class='card-body'><table class='table'><tbody>";
            foreach ($batchData as $key1 => $value1) {
                if(!empty($value1)){
            echo     "<tr><td><a href='#'>Acre</a></td><td><span class='fa fa-trash btn btn-link' style='float:right;'></span></td></tr>";
            }
            }
            echo     "</tbody></table></div></div></div>";
            }
    }

}
