<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Productcategory extends Admin_Controller
{

    function __construct()
    {
        parent::__construct();
        $this->load->model('Productcategory_model');
    }

    function index()
    {
        $this->load->library('form_validation');
        $this->form_validation->set_rules('productcategory', 'productcategory', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                'name' => $this->input->post('productcategory'),
                //'farm_id' => $this->session->userdata('active_farm'),
                'created_by' => $this->session->userdata('id')
            );
            $this->Productcategory_model->add_productcategory($params);
            $this->session->set_flashdata('success', 'Category Added Successfuly');
            redirect('productcategory');
        } else {

            $data['_view'] = 'productcategory/index';

            $this->load->view('layouts/main', $data);
        }
    }
    function get_list()
    {
        $columns = array(
            0 => 'name',
            1 => 'id'
        );

        // This is for sorting and pagination, it will mstly stay the same
        $limit = $this->input->post('length');
        $start = $this->input->post('start');
        $order = $columns[$this->input->post('order')[0]['column']];
        $dir = $this->input->post('order')[0]['dir'];
        // This is for sorting and pagination, it will mstly stay the same end


        $totalData = $this->Productcategory_model->get_all_productcategory_count();

        $totalFiltered = $totalData;

        if (empty($this->input->post('search')['value'])) {
            $posts = $this->Productcategory_model->get_all_productcategory($limit, $start, $order, $dir);
        } else {
            $search = $this->input->post('search')['value'];

            $posts =  $this->Productcategory_model->productcategory_search($limit, $start, $search, $order, $dir);

            $totalFiltered = $this->Productcategory_model->productcategory_search_count($search);
        }

        $data = array();
        if (!empty($posts)) {
            foreach ($posts as $post) {
                $nestedData['name'] = $post->name;
                $nestedData['actions'] = "<button class='btn btn-warning btn-xs btn-edit' code='" . $post->id . "'>Edit</button>&nbsp;<button class='btn btn-danger btn-xs btn-delete' code='" . $post->id . "'>Delete</button>";

                $data[] = $nestedData;
            }
        }

        $json_data = array(
            "draw"            => intval($this->input->post('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $data
        );

        echo json_encode($json_data);
    }


    public function edit_country($id)
    {
        # code...
    }

    public function delete_productcategory($id)
    {
        echo $this->Productcategory_model->delete_productcategory($id);
    }

    public function update_productcategory($id)
    {
        $this->load->library('form_validation');
        $this->form_validation->set_rules('name', 'label', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                'name' => $this->input->post('name')
            );

            echo $this->Productcategory_model->update_productcategory($id,$params);

        }
    }
}
