<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Animaltype_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        // Select All Query
        // $this->db->get('country')->result_array();
    }

    /*
     * Get animal_type by id
     */
    function get_animal_type($id)
    {
        $this->db->where('status!=',DELETED);
        return $this->db->get_where('animal_type', array('id' => $id))->row_array();
    }

    /*
     * Get all animal_type count
     */
    function get_all_animaltype_count()
    {
        $this->db->where('status!=',DELETED);
        $query = $this->db->get('animal_type'); 
        return $query->num_rows();
    }

    function get_animaltype_for_dd(){
        $this->db->where('status!=',DELETED);
        $this->db->select('animal_type.id, animal_type.type_of_animal as animal_name');
        $this->db->where('status', ACTIVE);
        return $this->db->get('animal_type')->result_array();
    }
    /*
     * Get all animal_type
     */
    function get_all_animaltype($limit, $start, $col, $dir)
    {
        $this->db->where('status!=',DELETED);
        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('animal_type'); 

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function animaltype_search($limit,$start,$search,$col,$dir)
    {
        
        $query = $this
                ->db
                ->where('status!=',DELETED)
                ->like('type_of_animal',$search) 
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('animal_type');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function animaltype_search_count($search)
    {
        
        $query = $this
                ->db
                ->where('animal_type.status!=',DELETED)
                ->like('type_of_animal',$search) 
                ->get('animal_type');
    
        return $query->num_rows();
    } 

    /*
     * function to add new animal_type
     */
    function add_animaltype($params)
    {
        $this->db->insert('animal_type', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update animal_type
     */
    function update_animal_type($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('animal_type', $params);
    }

    /*
     * function to delete animal_type
     */
    function delete_animal_type($id)
    {
        return $this->db->delete('animal_type', array('id' => $id));
    }

    function delete_animaltype($id){
        return $this->db->where('id',$id)
        ->update('animal_type',['status'=>DELETED]);
    }

    function update_animaltype($id,$data){
        
        return $this->db->where('id',$id)
        ->update('animal_type',$data);
    }

}
