<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Areauom_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        // Select All Query
        // $this->db->get('country')->result_array();
    }

    /*
     * Get brand by id
     */
    function get_brand($id)
    {
        return $this->db->get_where('brand', array('id' => $id))->row_array();
    }

    /*
     * Get all brand count
     */
    
    function get_areauom_for_dd(){
        $this->db->where('status!=',DELETED);
        $this->db->select('area_uom.id, area_uom.name as areauom_name');
        $this->db->where('status', ACTIVE);
        return $this->db->get('area_uom')->result_array();
    }
    // function province_by_country_id($id){
    //     $this->db->select('province.id, province.name as province_name');
    //     $this->db->where('status', ACTIVE);
    //     $this->db->where('country_id', $id);
    //     return $this->db->get('province')->result_array();
    // }
    /*
     * Get all brand
     */

     function get_all_areauom_count()
    {
        $this->db->where('status!=',DELETED);
        $query = $this->db->get('area_uom'); 
        return $query->num_rows();
    }
    
    function get_all_areauom($limit, $start, $col, $dir)
    {
        $this->db->where('status!=',DELETED);

        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('area_uom'); 

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function areauom_search($limit,$start,$search,$col,$dir)
    {
      
        $query = $this
                ->db
                ->where('area_uom.status!=',DELETED)
                ->like('area_uom.name',$search) 
              
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('area_uom');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function areauom_search_count($search)
    {
 
        $query = $this
                ->db
                ->where('area_uom.status!=',DELETED)
                ->like('area_uom.name',$search) 
              
                ->get('area_uom');
    
        return $query->num_rows();
    } 

    /*
     * function to add new brand
     */
    function add_areauom($params)
    {
        $this->db->insert('area_uom', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update brand
     */
    function update_brand($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('brand', $params);
    }

    /*
     * function to delete brand
     */
    function delete_brand($id)
    {
        return $this->db->delete('brand', array('id' => $id));
    }

    function delete_areauom($id){
        return $this->db->where('id',$id)
        ->update('area_uom',['status'=>DELETED]);
    }

    function update_areauom($id,$data){
        return $this->db->where('id',$id)
        ->update('area_uom',$data);
    }

}
