<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Bulkweight_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_batch_for_dd()
    {
        $this->db->select('animal_batch.id, animal_batch.code');
        $this->filter_by_active_farm();  
        return  $this->db->get('animal_batch')->result_array();
    }

    function get_animals_with_weight($batch_no)
    {
        $this->db->where('status!=',DELETED);
        $this->db->where('batch_id=',$batch_no);
        $this->db->select('fattening_animals.*');
        $this->filter_by_active_farm();
        $query = $this->db->get('fattening_animals');

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function get_last_weight($id)
    {
        $this->db->select('weight, date');
        $this->db->where('animal_id', $id);
        $this->db->order_by('id', 'DESC');
        $this->db->limit(1);
        $query = $this->db->get('fattening_animal_weight_history')->row();
        //print_r($this->db->last_query()); exit;
        return $query;
    }
}
