<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Country_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        // Select All Query
        // $this->db->get('country')->result_array();
    }

    /*
     * Get brand by id
     */
    function get_brand($id)
    {
        return $this->db->get_where('brand', array('id' => $id))->row_array();
    }

    /*
     * Get all brand count
     */
    function get_all_country_count()
    {
        $this->db->where('country.status!=',DELETED);
        $query = $this->db->get('country'); 
        return $query->num_rows();
    }

    function get_all_country_for_dd(){
        $this->db->where('country.status!=',DELETED);
        $this->db->select('country.id, country.name as country_name');
        $this->db->where('status', ACTIVE);
        return $this->db->order_by('country.name')
        ->get('country')->result_array();
    }
    /*
     * Get all brand
     */
    function get_all_country($limit, $start, $col, $dir)
    {
        $this->db->where('country.status!=',DELETED);
        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('country'); 

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function country_search($limit,$start,$search,$col,$dir)
    {
        $query = $this
                ->db
                ->where('country.status!=',DELETED)
                ->like('name',$search) 
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('country');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function country_search_count($search)
    {
        $this->db->where('country.status!=',DELETED);
        $query = $this
                ->db
                ->like('name',$search) 
                ->get('country');
    
        return $query->num_rows();
    } 

    /*
     * function to add new brand
     */
    function add_country($params)
    {
        $this->db->insert('country', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update brand
     */
    function update_brand($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('brand', $params);
    }

    /*
     * function to delete brand
     */
    function delete_brand($id)
    {
        return $this->db->delete('brand', array('id' => $id));
    }

    function delete_country($id)
    {
        return $this->db->where('id',$id)->update('country', array('status' => DELETED));
    }

    function update_country($id,$data){
        return $this->db->where('id',$id)->update('country', $data);
    }
}
