<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Currency_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        // Select All Query
        // $this->db->get('country')->result_array();
    }

    /*
     * Get brand by id
     */
    function get_brand($id)
    {
        return $this->db->get_where('brand', array('id' => $id))->row_array();
    }

    /*
     * Get all brand count
     */
    function get_all_currency_count()
    {
        $this->db->where('currency.status!=',DELETED);
        $query = $this->db->get('currency'); 
        return $query->num_rows();
    }

    function get_currency_for_dd(){
        $this->db->where('currency.status!=',DELETED);
        $this->db->select('currency.id, currency.name as currency_name,currency.symbol as currency_symbol');
        $this->db->where('status', ACTIVE);
        return $this->db->get('currency')->result_array();
    }
    /*
     * Get all brand
     */
    function get_all_currency($limit, $start, $col, $dir)
    {
        $this->db->where('currency.status!=',DELETED);
        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('currency'); 

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function currency_search($limit,$start,$search,$col,$dir)
    {
       
        $query = $this
                ->db
                ->where('currency.status!=',DELETED)
                // ->like('currency.name',$search) 
                // ->or_like('currency.symbol',$search)
                ->where(" ( currency.name LIKE '%$search%' OR currency.symbol  LIKE '%$search%' ) ") 
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('currency');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function currency_search_count($search)
    {
     
        $query = $this
                ->db
                // ->like('currency.name',$search) 
                // ->or_like('currency.symbol',$search) 
                ->where('currency.status!=',DELETED)
                ->where(" ( currency.name LIKE '%$search%' OR currency.symbol  LIKE '%$search%' ) ") 
                ->get('currency');
    
        return $query->num_rows();
    } 

    /*
     * function to add new brand
     */
    function add_currency($params)
    {
        $this->db->insert('currency', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update brand
     */
    function update_brand($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('brand', $params);
    }

    /*
     * function to delete brand
     */
    function delete_brand($id)
    {
        return $this->db->delete('brand', array('id' => $id));
    }

    function delete_currency($id)
    {
        return $this->db->where('id',$id)->update('currency', array('status' => DELETED));
    }

    function update_currency($id,$data)
    {
        return $this->db->where('id',$id)->update('currency', $data);
    }
}
