<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Currentstock_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_category_products($id)
    {
        $this->db->select('id, product_code, product_name');
        $this->filter_by_active_farm();
        $this->db->where('product_category_id', $id);
        $data['products'] =  $this->db->get('product')->result_array();
        return $data;
    }


    function get_products_search($params)
    {
        if(isset($params['todate']) && $params['todate'] != ""){
            $todate = "stocks.date_created <='".$params["todate"]."'";
            $this->db->where($todate);
        } else {
            $todate = "";
        }

        if(isset($params['category_product']) && $params['category_product'] != ""){
            $category_product = " product.product_category_id ='".$params["category_product"]."'";
            $this->db->where($category_product);
        } else {
            $category_product = "";
        }

        if(isset($params['product_id']) && $params['product_id'] != ""){
            $product_id = " stocks.item_id ='".$params["product_id"]."'";
            $this->db->where($product_id);
        } else {
            $product_id = "";
        }
        
        
        $results = array();
        $this->db->select('sum(stocks.quantity) AS stock, product.avg_cost AS avg_cost, product_category.name AS pro_name,
        product.product_code AS product_code, product.product_name AS product_name, 
        product.id AS product_id');
        $this->db->join('product as product', 'stocks.item_id=product.id', 'left join');
        $this->db->join('product_category as product_category', 'product.product_category_id=product_category.id', 'left join');
        $this->filter_by_active_farm('stocks');
        $this->db->group_by("stocks.item_id");
        $query = $this->db->get('stocks as stocks');
        
        //print_r($this->db->last_query()); exit;
        if ($query->num_rows() > 0) {
            $results = $query->result();
            //return $query->result();
        } 

        return $results;
        
    }
}
