<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        
    }

    

    function AnimalsCountByStatus($table, $farm_id)
    {
        $query = $this->db->query("SELECT
            COUNT(IF(status = '1', 1, NULL)) 'ACTIVE',
            COUNT(IF(status = '2', 1, NULL)) 'SUSPENDED',
            COUNT(IF(status = '3', 1, NULL)) 'PREGNENT',
            COUNT(IF(status = '4', 1, NULL)) 'HEIFER',
            COUNT(IF(status = '5', 1, NULL)) 'DISEASED',
            COUNT(IF(status = '6', 1, NULL)) 'QUARANTINE'
            FROM $table WHERE farm_id=$farm_id");
        
        
        return $query->row();
    }

    function AnimalsyeildMilk($farm_id)
    {
        $results = array();
        $query = $this->db->query("SELECT  
            `animals`.name as animal_name,
            `animals`.code as animal_code, 
            SUM(`milk_yeild`.`qty`) AS animalTotalQty
            FROM `milk_yeild` 
            LEFT JOIN `animals` ON (`milk_yeild`.`animal_id`=`animals`.`id`) 
            WHERE `milk_yeild`.`farm_id`=$farm_id AND MONTH(`milk_yeild`.`date`) = MONTH(CURRENT_DATE())
            AND YEAR(`milk_yeild`.`date`) = YEAR(CURRENT_DATE())
            GROUP BY `animal_id`
        ");
        
        if ($query->num_rows() > 0) {
            $results = $query->result();
        } 
        return $results;
    }

    function AnimalsmilkYeildByDate($farm_id){

        $results = array();
        $query = $this->db->query("SELECT `date`,
        round(SUM(if(routine = '1',qty,0)),2) 'Morning',
        round(SUM(if(routine = '2',qty,0)),2)  'Afternoon',
        round(SUM(if(routine = '3',qty,0)),2)  'Evening'
        
        FROM `milk_yeild` 
        WHERE `farm_id`=$farm_id AND  `date` >= DATE_SUB(CURDATE(), INTERVAL 10 DAY) 
        GROUP BY `date`
        ");
        
        if ($query->num_rows() > 0) {
            $results = $query->result();
        } 
        return $results;
    }

    /**
     * function to get current month's expense by cat.
     */
    function get_expense_by_categories(){
        $exps =  $this->db->where('MONTH(expense.date)=MONTH(CURRENT_DATE)',NULL,FALSE)
        ->select('COALESCE(SUM(expense.amount),0) AS total_expense,expense_category.name AS category')
        ->join('expense_category','expense.expense_cat_id=expense_category.id')
        ->group_by('expense_category.name')
        ->get('expense')
        ->result();

        // $cur_symbol = $this->get_active_farm_currency();

        $final = [
            'data'=>[],
            'labels'=>[],
            'month'=>date('F'),
            'currency_symbol'=> $this->get_active_farm_currency()
        ];

        foreach ($exps as $key => $value) {
            $final['data'][] = $value->total_expense;
            $final['labels'][] = $value->category;

        }

        return $final;
    }


    function get_active_farm_currency(){

        $cur = $this->db->where(['farm.id'=>$this->session->userdata('active_farm')])
        ->select('currency.symbol')
        ->join('currency','farm.currency_id=currency_id')
        ->get('farm')
        ->row();

        return ($cur)?$cur->symbol : ' /-';
    }

    
}
