<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Expensecategory_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        // Select All Query
        // $this->db->get('country')->result_array();
    }

    /*
     * Get expense_category by id
     */
    function get_expense_category($id)
    {
        $this->db->where('expense_category.status!=',DELETED);
        $this->filter_by_active_farm();
        return $this->db->get_where('expense_category', array('id' => $id))->row_array();
    }

    /*
     * Get all expense_category count
     */
    function get_all_expensecategory_count()
    {
        $this->db->where('expense_category.status!=',DELETED);

        $this->filter_by_active_farm();
        $query = $this->db->get('expense_category'); 
        return $query->num_rows();
    }

    function get_expensecategory_for_dd(){
        $this->db->where('expense_category.status!=',DELETED);
        $this->filter_by_active_farm();
        $this->db->select('expense_category.id, expense_category.name as expense_category_name');
        $this->db->where('status', ACTIVE);
        return $this->db->get('expense_category')->result_array();
    }
    /*
     * Get all expense_category
     */
    function get_all_expensecategory($limit, $start, $col, $dir)
    {
        $this->db->where('expense_category.status!=',DELETED);
        $this->filter_by_active_farm();
        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('expense_category'); 

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function expensecategory_search($limit,$start,$search,$col,$dir)
    {
        $this->db->where('expense_category.status!=',DELETED);
        $this->filter_by_active_farm();
        $query = $this
                ->db
                ->like('name',$search) 
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('expense_category');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function expensecategory_search_count($search)
    {
        $this->db->where('expense_category.status!=',DELETED);
        $this->filter_by_active_farm();
        $query = $this
                ->db
                ->like('name',$search) 
                ->get('expense_category');
    
        return $query->num_rows();
    } 

    /*
     * function to add new expense_category
     */
    function add_expensecategory($params)
    {
        $this->db->insert('expense_category', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update expense_category
     */
    function update_expense_category($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('expense_category', $params);
    }

    /*
     * function to delete expense_category
     */
    function delete_expense_category($id)
    {
        return $this->db->where(array('id' => $id))
        ->update('expense_category', array('status' => DELETED));
    }


    

}
