<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

use Mpdf\Tag\P;

class Feedcategory_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        // Select All Query
        // $this->db->get('country')->result_array();
    }

    /*
     * Get brand by id
     */
    function get_brand($id)
    {
        return $this->db->get_where('brand', array('id' => $id))->row_array();
    }

    /*
     * Get all brand count
     */
    function get_all_feedcategory_count()
    {
        $this->db->where('status!=',DELETED);
        $query = $this->db->get('feed_category'); 
        return $query->num_rows();
    }

    function get_feedcategory_for_dd(){
        $this->db->where('status!=',DELETED);
        $this->db->select('feed_category.id, feed_category.name as feed_category_name');
        $this->db->where('status', ACTIVE);
        return $this->db->get('feed_category')->result_array();
    }
    /*
     * Get all brand
     */
    function get_all_feedcategory($limit, $start, $col, $dir)
    {
        $this->db->where('status!=',DELETED);
        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('feed_category'); 

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function feedcategory_search($limit,$start,$search,$col,$dir)
    {
        
        $query = $this
                ->db
                ->where('status!=',DELETED)
                ->like('name',$search) 
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('feed_category');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function feedcategory_search_count($search)
    {
        
        $query = $this
                ->db
                ->where('status!=',DELETED)
                ->like('name',$search) 
                ->get('feed_category');
    
        return $query->num_rows();
    } 

    /*
     * function to add new brand
     */
    function add_feedcategory($params)
    {
        $this->db->insert('feed_category', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update brand
     */
    function update_brand($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('brand', $params);
    }

    /*
     * function to delete brand
     */
    function delete_brand($id)
    {
        return $this->db->delete('brand', array('id' => $id));
    }

    function delete_feedcategory($id){
        return $this->db->where('id',$id)->update('feed_category',['status'=>DELETED]);
    }

    function update_feedcategory($id,$data){
        return $this->db->where('id',$id)->update('feed_category',$data);
    }
}
