<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Itemuom_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        // Select All Query
        // $this->db->get('country')->result_array();
    }

    /*
     * Get brand by id
     */
   

    /*
     * Get all brand count
     */
    function get_all_itemuom_count()
    {
        $this->db->where('status!=',DELETED);
        $query = $this->db->get('item_uom'); 
        return $query->num_rows();
    }
    function get_itemuom_for_dd(){
        $this->db->where('status!=',DELETED);
        $this->db->select('item_uom.id AS id, item_uom.name as itemuom_name, item_uom.symbol as itemuom_symbol');
        $this->db->where('status', ACTIVE);
        return $this->db->get('item_uom')->result_array();
    }
    // function province_by_country_id($id){
    //     $this->db->select('province.id, province.name as province_name');
    //     $this->db->where('status', ACTIVE);
    //     $this->db->where('country_id', $id);
    //     return $this->db->get('province')->result_array();
    // }
    /*
     * Get all brand
     */
    function get_all_itemuom($limit, $start, $col, $dir)
    {
        $this->db->where('status!=',DELETED);

        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('item_uom'); 

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function areauom_search($limit,$start,$search,$col,$dir)
    {
      
        $query = $this
                ->db
                ->where('item_uom.status!=',DELETED)
                ->like('item_uom.name',$search) 
                ->like('item_uom.symbol',$search) 
              
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('item_uom');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function areauom_search_count($search)
    {
 
        $query = $this
                ->db
                ->where('item_uom.status!=',DELETED)
                ->like('item_uom.name',$search) 
                ->like('item_uom.symbol',$search) 
              
                ->get('item_uom');
    
        return $query->num_rows();
    } 

    /*
     * function to add new brand
     */
    function add_itemuom($params)
    {
        $this->db->insert('item_uom', $params);
        return $this->db->insert_id();
    }

    

    

    function delete_itemuom($id){
        return $this->db->where('id',$id)
        ->update('item_uom',['status'=>DELETED]);
    }

    function update_itemuom($id,$data){
        return $this->db->where('id',$id)
        ->update('item_uom',$data);
    }

}
