<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class LandManagementType_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    
    function get_all_LandManagementType_count()
    {
        $this->db->where('status!=',DELETED);
        $query = $this->db->get('land_management_type'); 
        return $query->num_rows();
    }

    
    function get_all_LandManagementType($limit, $start, $col, $dir)
    {
        $this->db->where('status!=',DELETED);
        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('land_management_type'); 

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function LandManagementType_search($limit,$start,$search,$col,$dir)
    {
       
        $query = $this
                ->db
                ->where('status!=',DELETED)
                ->where(" ( land_management_type LIKE '%$search%' ) ") 
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('land_management_type');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function LandManagementType_search_count($search)
    {
     
        $query = $this
                ->db
                ->where('status!=',DELETED)
                ->where(" ( land_management_type LIKE '%$search%' ) ") 
                ->get('land_management_type');
    
        return $query->num_rows();
    } 

    /*
     * function to add new brand
     */
    function add($params)
    {
        $this->db->insert('land_management_type', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update brand
     */
    function update_brand($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('brand', $params);
    }

    

    function delete_LandManagementType($id)
    {
        return $this->db->where('id',$id)->update('land_management_type', array('status' => DELETED));
    }

    function update_LandManagementType($id,$data)
    {
        return $this->db->where('id',$id)->update('land_management_type', $data);
    }
}
