<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Land_record_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }


   function add($table, $params)
    {
        $this->db->insert($table, $params);
        return $this->db->insert_id();
    }

    function batch_count(){
        $this->filter_by_active_farm();
        $this->db->where('status!=',DELETED);
        $query = $this->db->get('land_batch'); 
        //print_r($this->db->last_query()); exit;
        return $query->num_rows();
        
    }

    function get_invoiceno($type)
    {   
        // echo $type;exit;
        $this->db->where('land_type=',$type);
        $this->db->select('invoice_no');
        $query = $this->db->limit(1)->order_by('invoice_no','DESC')->get('land_batch');
         $run=$query->row_array();
         // echo $run['invoice_no'];exit;
         return $run['invoice_no']+1;
    }
}
