<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Partycategory_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        // Select All Query
        // $this->db->get('country')->result_array();
    }

    /*
     * Get party_category by id
     */
    function get_party_category($id)
    {
        $this->filter_by_active_farm();
        $this->db->where('status !=',DELETED);
        return $this->db->get_where('party_category', array('id' => $id))->row_array();
    }

    /*
     * Get party_category by type
     */
    function get_party_categories($type)
    {
        $this->filter_by_active_farm();
        $this->db->where('status !=',DELETED);
        return $this->db->order_by('party_category.name')->get_where('party_category', array('type' => $type))->result_array();
    }

    /*
     * Get all party_category count
     */
    function get_all_partycategory_count()
    {
        $this->filter_by_active_farm();
        $query = $this->db->where('status !=',DELETED)->get('party_category');
        return $query->num_rows();
    }

    function get_partycategory_for_dd()
    {
        $this->filter_by_active_farm();
        $this->db->select('party_category.id, party_category.name as party_category_name');
        $this->db->where('status !=',DELETED)->where('status', ACTIVE);
        
        return $this->db->get('party_category')->result_array();
    }
    /*
     * Get all party_category
     */
    function get_all_partycategory($limit, $start, $col, $dir)
    {
        $this->filter_by_active_farm();
        $this->db->where('status !=',DELETED)->select("party_category.*,IF(party_category.type='1','Customer','Supplier') AS pretty_type");
        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('party_category');

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function partycategory_search($limit, $start, $search, $col, $dir)
    {
        $this->filter_by_active_farm();
        $query = $this
            ->db->where('status !=',DELETED)
            ->select("party_category.*,IF(party_category.type='".PARTY_TYPE_CUSTOMER."','Customer','Supplier') AS pretty_type")
            ->like('name', $search)
            // ->like("IF(party_category.type='C','Customer','Supplier')", $search)
            ->limit($limit, $start)
            ->order_by($col, $dir)
            ->get('party_category');


        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function partycategory_search_count($search)
    {
        $this->filter_by_active_farm();
        $this->db->where('status !=',DELETED);
        // ->like("IF(party_category.type='C','Customer','Supplier')", $search);
        $query = $this
            ->db
            ->like('name', $search)
            ->get('party_category');

        return $query->num_rows();
    }

    /*
     * function to add new party_category
     */
    function add_partycategory($params)
    {
        $this->db->insert('party_category', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update party_category
     */
    function update_party_category($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('party_category', $params);
    }

    /*
     * function to delete party_category
     */
    function delete_party_category($id)
    {
        $this->db->where('id', $id)->update('party_category', array('status' => DELETED));
        return $this->db->affected_rows() > 0;
    }
}
