<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Productcategory_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        // Select All Query
        // $this->db->get('country')->result_array();
    }

    /*
     * Get brand by id
     */
    function get_brand($id)
    {
        return $this->db->get_where('brand', array('id' => $id))->row_array();
    }

    function get_code()
    {
        $this->filter_by_active_farm();
        $query = $this->db->get('product');
        $numrows =  $query->num_rows();
        return 'ITM' . sprintf('%06d', $numrows + 1);
    }

    /*
     * Get all brand count
     */
    function get_all_productcategory_count()
    {
        $this->db->where('product_category.status!=',DELETED);
        //$this->filter_by_active_farm('product_category');
        $query = $this->db->get('product_category'); 
        return $query->num_rows();
    }

    function get_productcategory_for_dd(){
        $this->db->where('product_category.status!=',DELETED);
        $this->db->select('product_category.id, product_category.name as product_category_name');
        //$this->filter_by_active_farm('product_category');
        $this->db->where('status', ACTIVE);
        return $this->db->get('product_category')->result_array();
    }
    /*
     * Get all brand
     */
    function get_all_productcategory($limit, $start, $col, $dir)
    {
        $this->db->where('product_category.status!=',DELETED);
        //$this->filter_by_active_farm('product_category');
        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('product_category'); 

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function productcategory_search($limit,$start,$search,$col,$dir)
    {
        $this->db->where('product_category.status!=',DELETED);
        //$this->filter_by_active_farm('product_category');
        $query = $this
                ->db
                ->like('name',$search) 
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('product_category');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function productcategory_search_count($search)
    {
        $this->db->where('product_category.status!=',DELETED);
        //$this->filter_by_active_farm('product_category');
        $query = $this
                ->db
                ->like('name',$search) 
                ->get('product_category');
    
        return $query->num_rows();
    } 

    /*
     * function to add new brand
     */
    function add_productcategory($params)
    {
        $this->db->insert('product_category', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update brand
     */
    function update_brand($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('brand', $params);
    }

    /*
     * function to delete brand
     */
    function delete_brand($id)
    {
        return $this->db->delete('brand', array('id' => $id));
    }

    function delete_productcategory($id){
        return $this->db->where('id',$id)
        ->update('product_category',['status'=>DELETED]);
    }

    function update_productcategory($id,$data){
        return $this->db->where('id',$id)
        ->update('product_category',$data);
    }

}
