<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Quarantine_animals_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        
    }

    function get_all_animals_count()
    {
        $this->filter_by_active_farm();
        $this->db->where('status', QUARANTINE);
        $query = $this->db->get('animals');

        return $query->num_rows();
    }
    
    function get_all_animals($limit, $start, $col, $dir)
    {
        // $this->db->select('a.*, af.name as father_name, am.name as mother_name, breed.breed_name, animal_type.type_of_animal as type,item_uom.symbol');
        // $this->db->join('animals as af', 'af.id = a.father_id', 'left outer');
        // $this->db->join('animals as am', 'am.id = a.mother_id', 'left outer');
        // $this->db->join('breed', 'breed.id = a.animal_breed');
        // $this->db->join('animal_type', 'animal_type.id = a.animal_type');
        // $this->db->join('item_uom', 'item_uom.id = a.item_uom_id', 'left outer');
        // $this->db->where('a.status', QUARANTINE);
        // $this->filter_by_active_farm('a');
        // $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('animals as a');
        // print_r($this->db->last_query());    exit;

        // if ($query->num_rows() > 0) {
        //     return $query->result();
        // } else {
        //     return null;
        // }
        $farm_id=$this->session->userdata('active_farm');
        // echo $farm_id;exit;
       $query= $this->db->query(' (SELECT  `a`.*, `af`.`name` as `father_name`, `am`.`name` as `mother_name`, `breed`.`breed_name`, `animal_type`.`type_of_animal` as `type`, `item_uom`.`symbol`
FROM `animals` as `a`
LEFT OUTER JOIN `animals` as `af` ON `af`.`id` = `a`.`father_id`
LEFT OUTER JOIN `animals` as `am` ON `am`.`id` = `a`.`mother_id`
JOIN `breed` ON `breed`.`id` = `a`.`animal_breed`
JOIN `animal_type` ON `animal_type`.`id` = `a`.`animal_type`
LEFT OUTER JOIN `item_uom` ON `item_uom`.`id` = `a`.`item_uom_id`
WHERE `a`.`status` = '.QUARANTINE.' AND a.farm_id='.$farm_id.' ORDER BY '.$col.' ASC
 LIMIT '.$limit.')
UNION ALL
(SELECT a.`id`, a.`code`, a.`avatar`, a.`name`, a.`weight`,a.`item_uom_id`, a.`dop`, a.`dob`, a.`sex`, a.`father_id`,a.`mother_id`,a.`created_by`, a.`date_created`, a.`status`, a.`animal_breed`, a.`animal_type`, a.`farm_id`, `af`.`name` as `father_name`, `am`.`name` as `mother_name`, `breed`.`breed_name`, `animal_type`.`type_of_animal` as `type`, `item_uom`.`symbol` FROM fattening_animals as `a` LEFT OUTER JOIN fattening_animals as `af` ON `af`.`id` = `a`.`father_id` LEFT OUTER JOIN fattening_animals as `am` ON `am`.`id` = `a`.`mother_id` JOIN `breed` ON `breed`.`id` = `a`.`animal_breed` JOIN `animal_type` ON `animal_type`.`id` = `a`.`animal_type` LEFT OUTER JOIN `item_uom` ON `item_uom`.`id` = `a`.`item_uom_id` WHERE `a`.`status` = '.QUARANTINE.' AND a.farm_id='.$farm_id.' ORDER BY '.$col.' ASC)
 LIMIT '.$limit.' ');  
         if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
   // print_r($this->db->last_query());    exit;   
    }

    function animals_search($limit, $start, $search, $col, $dir)
    {
        // $this->db->select('a.*, af.name as father_name, am.name as mother_name, breed.breed_name, animal_type.type_of_animal as type');
        $this->db->select('a.*, af.name as father_name, am.name as mother_name, breed.breed_name, animal_type.type_of_animal as type,item_uom.symbol');
        $this->db->join('animals as af', 'af.father_id = a.id', 'left outer');
        $this->db->join('animals as am', 'am.mother_id = a.id', 'left outer');
        $this->db->join('breed', 'breed.id = a.animal_breed');
        $this->db->join('animal_type', 'animal_type.id = a.animal_type');
        $this->db->join('item_uom', 'item_uom.id = a.item_uom_id', 'left outer');
        $this->db->where('a.status', QUARANTINE);
        $this->filter_by_active_farm('a');
        $query = $this
            ->db
            ->like('a.name', $search)
            ->or_like('a.code', $search)
            ->or_like('a.dob', $search)
            ->or_like('a.dop', $search)
            ->or_like('breed.breed_name', $search)
            ->or_like('animal_type.type_of_animal', $search)

            ->limit($limit, $start)
            ->order_by($col, $dir)
            ->get('animals as a');


        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function animals_search_count($search)
    {
        $this->db->select('a.*, af.name as father_name, am.name as mother_name, breed.breed_name, animal_type.type_of_animal as type');
        $this->db->join('animals as af', 'af.father_id = a.id', 'left outer');
        $this->db->join('animals as am', 'am.mother_id = a.id', 'left outer');
        $this->db->join('breed', 'breed.id = a.animal_breed');
        $this->db->join('animal_type', 'animal_type.id = a.animal_type');
        $this->db->join('item_uom', 'item_uom.id = a.item_uom_id', 'left outer');
        $this->db->where('a.status', QUARANTINE);
        $this->filter_by_active_farm('a');
        $query = $this
            ->db
            ->like('a.name', $search)
            ->or_like('a.code', $search)
            ->or_like('a.dob', $search)
            ->or_like('a.dop', $search)
            ->or_like('breed.breed_name', $search)
            ->or_like('animal_type.type_of_animal', $search)

            ->get('animals as a');

        return $query->num_rows();
    }

    function update_animal($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('animals', $params);
    }
    
}
