<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();

        // Select All Query
        // $this->db->get('country')->result_array();
    }

    /*
     * Get brand by id
     */
    function get_brand($id)
    {
        return $this->db->get_where('brand', array('id' => $id))->row_array();
    }

    /*
     * Get all brand count
     */
    function get_all_user_count()
    {
        $this->db->where('users.status!=',DELETED);
        $query = $this->db->get('users'); 
        return $query->num_rows();
    }

    function get_all_country_for_dd(){
        $this->db->select('country.id, country.name as country_name');
        $this->db->where('status', ACTIVE);
        return $this->db->get('country')->result_array();
    }
    /*
     * Get all brand
     */
    function get_all_user($limit, $start, $col, $dir)
    {
        $this->db->where('users.status!=',DELETED);
        $query = $this->db->limit($limit, $start)->order_by($col, $dir)->get('users'); 

        if ($query->num_rows() > 0) {
            return $query->result();
        } else {
            return null;
        }
    }

    function user_search($limit,$start,$search,$col,$dir)
    {
        $this->db->where('users.status!=',DELETED);

        $query = $this
                ->db
                ->where("( 
                    fname LIKE '%$search%' OR
                    lname LIKE '%$search%' OR
                    phone_no LIKE '%$search%' OR
                    email LIKE '%$search%' OR
                    mobile_no LIKE '%$search%'
                 )")
                ->limit($limit,$start)
                ->order_by($col,$dir)
                ->get('users');
        
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function user_search_count($search)
    {
        // $this->db->where('users.status!=',DELETED);

        $query = $this
                ->db
                ->where('users.status!=',DELETED)
                //    ->like('fname',$search) 
                // ->or_like('lname',$search) 
                // ->or_like('phone_no',$search) 
                // ->or_like('email',$search) 
                // ->or_like('mobile_no',$search)  
                ->where("( 
                    fname LIKE '%$search%' OR
                    lname LIKE '%$search%' OR
                    phone_no LIKE '%$search%' OR
                    email LIKE '%$search%' OR
                    mobile_no LIKE '%$search%'
                 )")
                ->get('users');
    
        return $query->num_rows();
    } 

    /*
     * function to add new brand
     */
    function add_user($params)
    {
        $this->db->insert('users', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update brand
     */
    function update_brand($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('brand', $params);
    }

    /*
     * function to delete brand
     */
    function delete_brand($id)
    {
        return $this->db->delete('brand', array('id' => $id));
    }

    function delete_user($id)
    {
        return $this->db->where('id',$id)->update('users', array('status' => DELETED));
    }

    function get_user($id){
        return $this->db->where('id',$id)
        ->get('users')
        ->row();
    }

}
